name: Test Dispatch Event
run-name: Testing ${{ github.event.inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: The name of the package to check
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Run npx command
      shell: 'script -q -e -c "bash {0}"'
      run: npx @n8n/scan-community-package ${{ github.event.inputs.package }}
    - name: Run Audit
      shell: 'script -q -e -c "bash {0}"'
      run: npm i ${{ github.event.inputs.package }} && npm audit ${{ github.event.inputs.package }}